version: '3.8'
services:
  kafka-broker-1:
    image: raft
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_UUID=mV83KWUrRaG1yxp1wQ7rRA
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    networks:
      - raft

  kafka-broker-2:
    image: raft
    container_name: kafka-broker-2
    ports:
      - "9093:9092"
    environment:
      - KAFKA_UUID=mV83KWUrRaG1yxp1wQ7rRA
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=2
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    networks:
      - raft

  kafka-broker-3:
    image: raft
    container_name: kafka-broker-3
    ports:
      - "9094:9092"
    environment:
      - KAFKA_UUID=mV83KWUrRaG1yxp1wQ7rRA
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=3
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    networks:
      - raft

networks:
  raft:
    name: raft